//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0428_REST_DB_Client_.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/_0428_REST_DB_SERVER_")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        _0428_REST_DB_Client_.ServiceReference1.Member[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(System.AsyncCallback callback, object asyncState);
        
        _0428_REST_DB_Client_.ServiceReference1.Member[] EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostData", ReplyAction="http://tempuri.org/IService1/PostDataResponse")]
        bool PostData(string name, int age, string phone);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/PostData", ReplyAction="http://tempuri.org/IService1/PostDataResponse")]
        System.IAsyncResult BeginPostData(string name, int age, string phone, System.AsyncCallback callback, object asyncState);
        
        bool EndPostData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutData", ReplyAction="http://tempuri.org/IService1/PutDataResponse")]
        bool PutData(string name, int age, string phone);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/PutData", ReplyAction="http://tempuri.org/IService1/PutDataResponse")]
        System.IAsyncResult BeginPutData(string name, int age, string phone, System.AsyncCallback callback, object asyncState);
        
        bool EndPutData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteData", ReplyAction="http://tempuri.org/IService1/DeleteDataResponse")]
        bool DeleteData(string name);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteData", ReplyAction="http://tempuri.org/IService1/DeleteDataResponse")]
        System.IAsyncResult BeginDeleteData(string name, System.AsyncCallback callback, object asyncState);
        
        bool EndDeleteData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : _0428_REST_DB_Client_.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _0428_REST_DB_Client_.ServiceReference1.Member[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_0428_REST_DB_Client_.ServiceReference1.Member[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PostDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PutDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<_0428_REST_DB_Client_.ServiceReference1.IService1>, _0428_REST_DB_Client_.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostDataDelegate;
        
        private EndOperationDelegate onEndPostDataDelegate;
        
        private System.Threading.SendOrPostCallback onPostDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginPutDataDelegate;
        
        private EndOperationDelegate onEndPutDataDelegate;
        
        private System.Threading.SendOrPostCallback onPutDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDataDelegate;
        
        private EndOperationDelegate onEndDeleteDataDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteDataCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<PostDataCompletedEventArgs> PostDataCompleted;
        
        public event System.EventHandler<PutDataCompletedEventArgs> PutDataCompleted;
        
        public event System.EventHandler<DeleteDataCompletedEventArgs> DeleteDataCompleted;
        
        public _0428_REST_DB_Client_.ServiceReference1.Member[] GetData() {
            return base.Channel.GetData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _0428_REST_DB_Client_.ServiceReference1.Member[] EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetData(callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            _0428_REST_DB_Client_.ServiceReference1.Member[] retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync() {
            this.GetDataAsync(null);
        }
        
        public void GetDataAsync(object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, null, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public bool PostData(string name, int age, string phone) {
            return base.Channel.PostData(name, age, phone);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPostData(string name, int age, string phone, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostData(name, age, phone, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndPostData(System.IAsyncResult result) {
            return base.Channel.EndPostData(result);
        }
        
        private System.IAsyncResult OnBeginPostData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            int age = ((int)(inValues[1]));
            string phone = ((string)(inValues[2]));
            return this.BeginPostData(name, age, phone, callback, asyncState);
        }
        
        private object[] OnEndPostData(System.IAsyncResult result) {
            bool retVal = this.EndPostData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPostDataCompleted(object state) {
            if ((this.PostDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostDataCompleted(this, new PostDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostDataAsync(string name, int age, string phone) {
            this.PostDataAsync(name, age, phone, null);
        }
        
        public void PostDataAsync(string name, int age, string phone, object userState) {
            if ((this.onBeginPostDataDelegate == null)) {
                this.onBeginPostDataDelegate = new BeginOperationDelegate(this.OnBeginPostData);
            }
            if ((this.onEndPostDataDelegate == null)) {
                this.onEndPostDataDelegate = new EndOperationDelegate(this.OnEndPostData);
            }
            if ((this.onPostDataCompletedDelegate == null)) {
                this.onPostDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostDataCompleted);
            }
            base.InvokeAsync(this.onBeginPostDataDelegate, new object[] {
                        name,
                        age,
                        phone}, this.onEndPostDataDelegate, this.onPostDataCompletedDelegate, userState);
        }
        
        public bool PutData(string name, int age, string phone) {
            return base.Channel.PutData(name, age, phone);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPutData(string name, int age, string phone, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPutData(name, age, phone, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndPutData(System.IAsyncResult result) {
            return base.Channel.EndPutData(result);
        }
        
        private System.IAsyncResult OnBeginPutData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            int age = ((int)(inValues[1]));
            string phone = ((string)(inValues[2]));
            return this.BeginPutData(name, age, phone, callback, asyncState);
        }
        
        private object[] OnEndPutData(System.IAsyncResult result) {
            bool retVal = this.EndPutData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPutDataCompleted(object state) {
            if ((this.PutDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PutDataCompleted(this, new PutDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PutDataAsync(string name, int age, string phone) {
            this.PutDataAsync(name, age, phone, null);
        }
        
        public void PutDataAsync(string name, int age, string phone, object userState) {
            if ((this.onBeginPutDataDelegate == null)) {
                this.onBeginPutDataDelegate = new BeginOperationDelegate(this.OnBeginPutData);
            }
            if ((this.onEndPutDataDelegate == null)) {
                this.onEndPutDataDelegate = new EndOperationDelegate(this.OnEndPutData);
            }
            if ((this.onPutDataCompletedDelegate == null)) {
                this.onPutDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPutDataCompleted);
            }
            base.InvokeAsync(this.onBeginPutDataDelegate, new object[] {
                        name,
                        age,
                        phone}, this.onEndPutDataDelegate, this.onPutDataCompletedDelegate, userState);
        }
        
        public bool DeleteData(string name) {
            return base.Channel.DeleteData(name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteData(string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteData(name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndDeleteData(System.IAsyncResult result) {
            return base.Channel.EndDeleteData(result);
        }
        
        private System.IAsyncResult OnBeginDeleteData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return this.BeginDeleteData(name, callback, asyncState);
        }
        
        private object[] OnEndDeleteData(System.IAsyncResult result) {
            bool retVal = this.EndDeleteData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteDataCompleted(object state) {
            if ((this.DeleteDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteDataCompleted(this, new DeleteDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteDataAsync(string name) {
            this.DeleteDataAsync(name, null);
        }
        
        public void DeleteDataAsync(string name, object userState) {
            if ((this.onBeginDeleteDataDelegate == null)) {
                this.onBeginDeleteDataDelegate = new BeginOperationDelegate(this.OnBeginDeleteData);
            }
            if ((this.onEndDeleteDataDelegate == null)) {
                this.onEndDeleteDataDelegate = new EndOperationDelegate(this.OnEndDeleteData);
            }
            if ((this.onDeleteDataCompletedDelegate == null)) {
                this.onDeleteDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteDataCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDataDelegate, new object[] {
                        name}, this.onEndDeleteDataDelegate, this.onDeleteDataCompletedDelegate, userState);
        }
    }
}
